In [10]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("aac_intakes_outcomes.csv")

In [17]:
total_by_breedType = data.groupby("breed").count()["animal_type"]
total_by_breedType = total_by_breedType.reset_index()
total_by_breedType = total_by_breedType.rename(columns =  {"breed":"Breed", "animal_type":"Totals"})
total_by_breedType

                                              Breed  Totals
0                                    Abyssinian Mix       4
1                                 Affenpinscher Mix       7
2                                  Afghan Hound Mix       1
3                   Afghan Hound/Labrador Retriever       1
4                                       African Mix       1
5                                  Airedale Terrier       1
6                              Airedale Terrier Mix      15
7                    Airedale Terrier/Irish Terrier       1
8               Airedale Terrier/Labrador Retriever       2
9              Airedale Terrier/Miniature Schnauzer       1
10                      Airedale Terrier/Otterhound       1
11                                       Akbash Mix       5
12                                            Akita       7
13                                        Akita Mix      40
14                      Akita/Australian Cattle Dog       3
15                           Akita/Belgian Malinois       2
16                              Akita/Border Collie       3
17                            Akita/German Shepherd       2
18                             Akita/Great Pyrenees       1
19                         Akita/Labrador Retriever       1
20                                    Akita/Mastiff       1
21                                   Akita/Pit Bull       2
22                             Akita/Siberian Husky       4
23                                    Alaskan Husky       9
24                                Alaskan Husky Mix      57
25                Alaskan Husky/Australian Shepherd       3
26                      Alaskan Husky/Border Collie       1
27                    Alaskan Husky/German Shepherd       4
28                 Alaskan Husky/Labrador Retriever       1
29                                 Alaskan Malamute       5
...                                             ...     ...
2125         Wire Hair Fox Terrier/Golden Retriever       1
2126      Wire Hair Fox Terrier/Miniature Schnauzer       1
2127                Wirehaired Pointing Griffon Mix       9
2128                                       Wren Mix       1
2129                              Yorkshire Terrier      46
2130                          Yorkshire Terrier Mix     447
2131           Yorkshire Terrier/Australian Terrier       1
2132               Yorkshire Terrier/Border Terrier       6
2133                Yorkshire Terrier/Bruss Griffon       2
2134                Yorkshire Terrier/Cairn Terrier      10
2135           Yorkshire Terrier/Chihuahua Longhair       9
2136          Yorkshire Terrier/Chihuahua Shorthair      23
2137              Yorkshire Terrier/Chinese Crested       1
2138                    Yorkshire Terrier/Dachshund       1
2139           Yorkshire Terrier/Dachshund Wirehair       1
2140                     Yorkshire Terrier/Havanese       2
2141         Yorkshire Terrier/Jack Russell Terrier       2
2142                   Yorkshire Terrier/Lhasa Apso       2
2143                      Yorkshire Terrier/Maltese       7
2144             Yorkshire Terrier/Miniature Poodle      25
2145          Yorkshire Terrier/Miniature Schnauzer      16
2146              Yorkshire Terrier/Norfolk Terrier       2
2147       Yorkshire Terrier/Parson Russell Terrier       1
2148                   Yorkshire Terrier/Pomeranian       2
2149                  Yorkshire Terrier/Rat Terrier       7
2150                     Yorkshire Terrier/Shih Tzu       3
2151  Yorkshire Terrier/Soft Coated Wheaten Terrier       1
2152              Yorkshire Terrier/Standard Poodle       1
2153                   Yorkshire Terrier/Toy Poodle       2
2154            Yorkshire Terrier/Yorkshire Terrier       1

[2155 rows x 2 columns]